In [3]:
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
import pickle

In [4]:
data=sns.load_dataset('tips')
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
data.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
dummies = pd.get_dummies(data[['smoker','sex', 'day','time']],drop_first=1).astype(int)

In [8]:
data=data.drop(columns=['smoker','sex', 'day','time'])

In [9]:
data=pd.concat([data,dummies],axis=1)

In [10]:
X=data.drop('tip',axis=1)
y=data['tip']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
model=LinearRegression()

In [13]:
model.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred=np.round(model.predict(X_test),2)

In [15]:
y_test

24     3.18
6      2.00
153    2.00
211    5.16
198    2.00
176    2.00
192    2.56
124    2.52
9      3.23
101    3.00
45     3.00
233    1.47
117    1.50
177    2.00
82     1.83
146    1.36
200    4.00
15     3.92
66     2.47
142    5.00
33     2.45
19     3.35
109    4.00
30     1.45
186    3.50
120    2.31
10     1.71
73     5.00
159    2.00
156    5.00
112    4.00
218    1.44
25     2.34
60     3.21
18     3.50
119    2.92
97     1.50
197    5.00
139    2.75
241    2.00
75     1.25
127    2.00
113    2.55
16     1.67
196    2.00
67     1.00
168    1.61
38     2.31
195    1.44
Name: tip, dtype: float64

In [16]:
temp=pd.DataFrame({'actual':y_test,'pred':y_pred})

In [17]:
temp

     actual  pred
24     3.18  2.91
6      2.00  2.00
153    2.00  3.96
211    5.16  3.76
198    2.00  2.15
176    2.00  2.67
192    2.56  3.64
124    2.52  2.29
9      3.23  2.57
101    3.00  2.46
45     3.00  2.90
233    1.47  2.06
117    1.50  2.12
177    2.00  2.35
82     1.83  1.83
146    1.36  3.11
200    4.00  2.95
15     3.92  3.22
66     2.47  2.57
142    5.00  5.74
33     2.45  3.43
19     3.35  3.23
109    4.00  2.17
30     1.45  1.94
186    3.50  3.16
120    2.31  2.25
10     1.71  2.14
73     5.00  3.21
159    2.00  3.20
156    5.00  6.67
112    4.00  5.01
218    1.44  1.58
25     2.34  3.19
60     3.21  2.77
18     3.50  2.98
119    2.92  3.86
97     1.50  2.17
197    5.00  5.47
139    2.75  2.36
241    2.00  2.99
75     1.25  2.03
127    2.00  2.48
113    2.55  3.44
16     1.67  2.36
196    2.00  1.93
67     1.00  0.87
168    1.61  1.82
38     2.31  3.04
195    1.44  1.85

In [18]:
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
mse,r2

(0.703195918367347, 0.43743036908267985)

In [19]:
with open("linear_model.pkl", "wb") as f:
    pickle.dump(model, f)